import { NestFactory } from "@nestjs/core";
import { AppModule } from "./app.module";
import supertokens from "supertokens-node";
import { SuperTokensExceptionFilter } from "supertokens-nestjs";
import crypto from "crypto";
import os from "os";

import { SwaggerModule, DocumentBuilder } from "@nestjs/swagger";
import { readFile, writeFile } from "fs/promises";
import {
  FRONTEND_HOST,
  SUPERTOKENS_HOST,
} from "./grassroots-shared/local-constants";

import openapiTS, { astToString } from "openapi-typescript";

// auto-generated by the "PluginMetadataGenerator"
import metadata from "./metadata";
import path from "path";
import { ValidationPipe } from "@nestjs/common";

const openAPISchemaPath = "./openAPI.json";
const openAPITSSchemaPath = "./src/grassroots-shared/openAPI.ts";

process.on("unhandledRejection", (err) => {
  console.error("There was an uncaught error", err);
  process.exit(1);
});

async function bootstrap(): Promise<void> {
  const app = await NestFactory.create(AppModule);

  app.enableCors({
    origin: [SUPERTOKENS_HOST, FRONTEND_HOST],
    allowedHeaders: ["Content-Type", ...supertokens.getAllCORSHeaders()],
    credentials: true,
  });
  app.useGlobalFilters(new SuperTokensExceptionFilter());
  app.useGlobalPipes(new ValidationPipe());
  app.setGlobalPrefix("api");

  await app.listen(process.env.PORT ?? 3003);

  const config = new DocumentBuilder()
    .setTitle("Grassroots")
    .setDescription("The Grassroots API description")
    .setVersion("0.0")
    .build();

  await SwaggerModule.loadPluginMetadata(metadata);
  const openAPI = SwaggerModule.createDocument(app, config, {
    autoTagControllers: true,
  });

  const openAPIStr = JSON.stringify(openAPI, null, 2);
  const openAPIHash = crypto
    .createHash("sha1")
    .update(openAPIStr)
    .digest("base64");

  const openAPIHashPath = path.join(os.tmpdir(), "nestOpenAPIHash");
  const lastHash = await readFile(openAPIHashPath, "utf8")
    .then((s) => {
      return s;
    })
    .catch(() => null);

  // The OpenAPI Spec has changed, due some post processing.
  if (openAPIHash != lastHash) {
    await writeFile(openAPIHashPath, openAPIHash);
    await writeFile(openAPISchemaPath, openAPIStr);
    console.log("Updating OpenAPI Schema TS bindings");
    const ast = await openapiTS(openAPIStr);
    const contents = astToString(ast);
    await writeFile(openAPITSSchemaPath, contents);
    console.log("Done updating OpenAPI Schema TS bindings");
  } else {
    console.log("Skip updating OpenAPI");
  }
}

void bootstrap();
