#!/bin/bash
npx concurrently \
  "npm test" \
  "npx syncpack list-mismatches" \
  "npx tsc --noEmit --project grassroots-backend" \
  "npx tsc --noEmit --project grassroots-frontend" \

npx lint-staged
